import axios from 'axios'

//action types

const GET_DONATION_TOTAL = 'GET_DONATION_TOTAL';
const GET_CURRENT_MONTHLY_TOTAL = 'GET_CURRENT_MONTHLY_TOTAL';
const GET_SELECTED_CHARITY = 'GET_SELECTED_CHARITY';
const GET_PREVIOUS_CHARITIES = 'GET_PREVIOUS_CHARITIES';

